{{- with .Values.favorite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-config-map
  {{- template "mychart.labels" $ }}
data:
  release: {{ $.Release.Name }}
  food: {{ .food | title | quote }}
  flavor: |- 
  {{- range .flavor }}
    -{{ . | title | quote }}
  {{- end }}
  drink: {{ .drink | title | quote }}
  place: {{ .place | title | quote }}
  {{- $files := $.Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}
{{- end }}
