name: Lint And Test Chart
on:
  push:
    branches:
        - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Set up Helm
              uses: azure/setup-helm@v4.2.0
              with:
                version: v3.17.0
          - name: lint
              run: |
                helm lint ./charts/helm-chart
