name: Lint test
run-name: ${{ github.actor }} is learning GitHub Action
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - name: lint
        run: |
          helm lint ./charts/helm-chart



